---
loopback: 10.255.0.3
mgmt_address: 10.10.99.3
stp_root_vlans: [20, 30]
stp_secondary_vlans: [10, 99]
svi_addresses:
  10: 10.10.10.3
  20: 10.10.20.3
  30: 10.10.30.3
  99: 10.10.99.3
downlinks:
  - interface: GigabitEthernet1/0/1
    peer: acc01
    peer_interface: GigabitEthernet1/0/50
  - interface: GigabitEthernet1/0/2
    peer: acc02
    peer_interface: GigabitEthernet1/0/50
peer_link:
  interface: TenGigabitEthernet1/0/2
  peer: dist01
  peer_interface: TenGigabitEthernet1/0/2
  address: 10.255.1.5
  prefix_length: 31
routed_links:
  - interface: TenGigabitEthernet1/0/1
    peer: core01
    peer_interface: TenGigabitEthernet0/0/1
    address: 10.255.1.3
    prefix_length: 31
